from flask_wtf import Form
from wtforms import StringField, SelectField, SelectMultipleField, DateTimeField, BooleanField, DecimalField
from wtforms.validators import DataRequired


class CountryForm(Form):
    country_from = SelectField(
                                'Source Country',
                                validators=[DataRequired("Please select the country")],
                                choices=[
                                            ('Aruba',	'Aruba'),
                                            ('Afghanistan',	'Afghanistan'),
                                            ('Angola',	'Angola'),
                                            ('Albania',	'Albania'),
                                            ('United Arab Emirates',	'United Arab Emirates'),
                                            ('Argentina',	'Argentina'),
                                            ('Armenia',	'Armenia'),
                                            ('Antigua and Barbuda',	'Antigua and Barbuda'),
                                            ('Australia',	'Australia'),
                                            ('Austria',	'Austria'),
                                            ('Azerbaijan',	'Azerbaijan'),
                                            ('Burundi',	'Burundi'),
                                            ('Belgium',	'Belgium'),
                                            ('Benin',	'Benin'),
                                            ('Burkina Faso',	'Burkina Faso'),
                                            ('Bangladesh',	'Bangladesh'),
                                            ('Bulgaria',	'Bulgaria'),
                                            ('Bahrain',	'Bahrain'),
                                            ('Bahamas, The',	'Bahamas The'),
                                            ('Bosnia and Herzegovina',	'Bosnia and Herzegovina'),
                                            ('Belarus',	'Belarus'),
                                            ('Belize',	'Belize'),
                                            ('Bermuda',	'Bermuda'),
                                            ('Bolivia',	'Bolivia'),
                                            ('Brazil',	'Brazil'),
                                            ('Barbados',	'Barbados'),
                                            ('Brunei Darussalam',	'Brunei Darussalam'),
                                            ('Bhutan',	'Bhutan'),
                                            ('Botswana',	'Botswana'),
                                            ('Central African Republic',	'Central African Republic'),
                                            ('Canada',	'Canada'),
                                            ('Switzerland',	'Switzerland'),
                                            ('Chile',	'Chile'),
                                            ('China',	'China'),
                                            ('Cote d Ivoire',	'Cote d Ivoire'),
                                            ('Cameroon',	'Cameroon'),
                                            ('Congo, Dem. Rep.',	'Congo Dem. Rep.'),
                                            ('Congo, Rep.',	'Congo Rep.'),
                                            ('Colombia',	'Colombia'),
                                            ('Comoros',	'Comoros'),
                                            ('Cabo Verde',	'Cabo Verde'),
                                            ('Costa Rica',	'Costa Rica'),
                                            ('Curacao',	'Curacao'),
                                            ('Cayman Islands',	'Cayman Islands'),
                                            ('Cyprus',	'Cyprus'),
                                            ('Czech Republic',	'Czech Republic'),
                                            ('Germany',	'Germany'),
                                            ('Djibouti',	'Djibouti'),
                                            ('Dominica',	'Dominica'),
                                            ('Denmark',	'Denmark'),
                                            ('Dominican Republic',	'Dominican Republic'),
                                            ('Algeria',	'Algeria'),
                                            ('Ecuador',	'Ecuador'),
                                            ('Egypt, Arab Rep.',	'Egypt Arab Rep.'),
                                            ('Eritrea',	'Eritrea'),
                                            ('Spain',	'Spain'),
                                            ('Estonia',	'Estonia'),
                                            ('Ethiopia',	'Ethiopia'),
                                            ('Finland',	'Finland'),
                                            ('Fiji',	'Fiji'),
                                            ('France',	'France'),
                                            ('Micronesia, Fed. Sts.',	'Micronesia Fed. Sts.'),
                                            ('Gabon',	'Gabon'),
                                            ('United Kingdom',	'United Kingdom'),
                                            ('Georgia',	'Georgia'),
                                            ('Ghana',	'Ghana'),
                                            ('Guinea',	'Guinea'),
                                            ('Gambia, The',	'Gambia The'),
                                            ('Guinea-Bissau',	'Guinea-Bissau'),
                                            ('Equatorial Guinea',	'Equatorial Guinea'),
                                            ('Greece',	'Greece'),
                                            ('Grenada',	'Grenada'),
                                            ('Guatemala',	'Guatemala'),
                                            ('Guyana',	'Guyana'),
                                            ('Hong Kong SAR, China',	'Hong Kong SAR China'),
                                            ('Honduras',	'Honduras'),
                                            ('Croatia',	'Croatia'),
                                            ('Haiti',	'Haiti'),
                                            ('Hungary',	'Hungary'),
                                            ('Indonesia',	'Indonesia'),
                                            ('India',	'India'),
                                            ('Ireland',	'Ireland'),
                                            ('Iran, Islamic Rep.',	'Iran Islamic Rep.'),
                                            ('Iraq',	'Iraq'),
                                            ('Iceland',	'Iceland'),
                                            ('Israel',	'Israel'),
                                            ('Italy',	'Italy'),
                                            ('Jamaica',	'Jamaica'),
                                            ('Jordan',	'Jordan'),
                                            ('Japan',	'Japan'),
                                            ('Kazakhstan',	'Kazakhstan'),
                                            ('Kenya',	'Kenya'),
                                            ('Kyrgyz Republic',	'Kyrgyz Republic'),
                                            ('Cambodia',	'Cambodia'),
                                            ('Kiribati',	'Kiribati'),
                                            ('St. Kitts and Nevis',	'St. Kitts and Nevis'),
                                            ('Korea, Rep.',	'Korea Rep.'),
                                            ('Kuwait',	'Kuwait'),
                                            ('Lao PDR',	'Lao PDR'),
                                            ('Lebanon',	'Lebanon'),
                                            ('Liberia',	'Liberia'),
                                            ('Libya',	'Libya'),
                                            ('St. Lucia',	'St. Lucia'),
                                            ('Sri Lanka',	'Sri Lanka'),
                                            ('Lesotho',	'Lesotho'),
                                            ('Lithuania',	'Lithuania'),
                                            ('Luxembourg',	'Luxembourg'),
                                            ('Latvia',	'Latvia'),
                                            ('Macao SAR, China',	'Macao SAR China'),
                                            ('Morocco',	'Morocco'),
                                            ('Moldova',	'Moldova'),
                                            ('Madagascar',	'Madagascar'),
                                            ('Maldives',	'Maldives'),
                                            ('Mexico',	'Mexico'),
                                            ('Marshall Islands',	'Marshall Islands'),
                                            ('North Macedonia',	'North Macedonia'),
                                            ('Mali',	'Mali'),
                                            ('Malta',	'Malta'),
                                            ('Myanmar',	'Myanmar'),
                                            ('Montenegro',	'Montenegro'),
                                            ('Mongolia',	'Mongolia'),
                                            ('Mozambique',	'Mozambique'),
                                            ('Mauritania',	'Mauritania'),
                                            ('Mauritius',	'Mauritius'),
                                            ('Malawi',	'Malawi'),
                                            ('Malaysia',	'Malaysia'),
                                            ('Namibia',	'Namibia'),
                                            ('Niger',	'Niger'),
                                            ('Nigeria',	'Nigeria'),
                                            ('Nicaragua',	'Nicaragua'),
                                            ('Netherlands',	'Netherlands'),
                                            ('Norway',	'Norway'),
                                            ('Nepal',	'Nepal'),
                                            ('Nauru',	'Nauru'),
                                            ('New Zealand',	'New Zealand'),
                                            ('Oman',	'Oman'),
                                            ('Pakistan',	'Pakistan'),
                                            ('Panama',	'Panama'),
                                            ('Peru',	'Peru'),
                                            ('Philippines',	'Philippines'),
                                            ('Palau',	'Palau'),
                                            ('Papua New Guinea',	'Papua New Guinea'),
                                            ('Poland',	'Poland'),
                                            ('Puerto Rico',	'Puerto Rico'),
                                            ('Portugal',	'Portugal'),
                                            ('Paraguay',	'Paraguay'),
                                            ('West Bank and Gaza',	'West Bank and Gaza'),
                                            ('Qatar',	'Qatar'),
                                            ('Romania',	'Romania'),
                                            ('Russian Federation',	'Russian Federation'),
                                            ('Rwanda',	'Rwanda'),
                                            ('Saudi Arabia',	'Saudi Arabia'),
                                            ('Sudan',	'Sudan'),
                                            ('Senegal',	'Senegal'),
                                            ('Singapore',	'Singapore'),
                                            ('Solomon Islands',	'Solomon Islands'),
                                            ('Sierra Leone',	'Sierra Leone'),
                                            ('El Salvador',	'El Salvador'),
                                            ('San Marino',	'San Marino'),
                                            ('Somalia',	'Somalia'),
                                            ('Serbia',	'Serbia'),
                                            ('Sao Tome and Principe',	'Sao Tome and Principe'),
                                            ('Suriname',	'Suriname'),
                                            ('Slovak Republic',	'Slovak Republic'),
                                            ('Slovenia',	'Slovenia'),
                                            ('Sweden',	'Sweden'),
                                            ('Eswatini',	'Eswatini'),
                                            ('Sint Maarten (Dutch part)',	'Sint Maarten (Dutch part)'),
                                            ('Seychelles',	'Seychelles'),
                                            ('Turks and Caicos Islands',	'Turks and Caicos Islands'),
                                            ('Chad',	'Chad'),
                                            ('Togo',	'Togo'),
                                            ('Thailand',	'Thailand'),
                                            ('Tajikistan',	'Tajikistan'),
                                            ('Turkmenistan',	'Turkmenistan'),
                                            ('Timor-Leste',	'Timor-Leste'),
                                            ('Tonga',	'Tonga'),
                                            ('Trinidad and Tobago',	'Trinidad and Tobago'),
                                            ('Tunisia',	'Tunisia'),
                                            ('Turkey',	'Turkey'),
                                            ('Tuvalu',	'Tuvalu'),
                                            ('Tanzania',	'Tanzania'),
                                            ('Uganda',	'Uganda'),
                                            ('Ukraine',	'Ukraine'),
                                            ('Uruguay',	'Uruguay'),
                                            ('United States',	'United States'),
                                            ('Uzbekistan',	'Uzbekistan'),
                                            ('St. Vincent and the Grenadines',	'St. Vincent and the Grenadines'),
                                            ('British Virgin Islands',	'British Virgin Islands'),
                                            ('Vietnam',	'Vietnam'),
                                            ('Vanuatu',	'Vanuatu'),
                                            ('Samoa',	'Samoa'),
                                            ('Kosovo',	'Kosovo'),
                                            ('South Africa',	'South Africa'),
                                            ('Zambia',	'Zambia'),
                                            ('Zimbabwe',	'Zimbabwe')])
    country_to = SelectField(
    'Target Country',validators=[DataRequired("Please select the country")],
    choices=[
            ('Aruba',	'Aruba'),
            ('Afghanistan',	'Afghanistan'),
            ('Angola',	'Angola'),
            ('Albania',	'Albania'),
            ('United Arab Emirates',	'United Arab Emirates'),
            ('Argentina',	'Argentina'),
            ('Armenia',	'Armenia'),
            ('Antigua and Barbuda',	'Antigua and Barbuda'),
            ('Australia',	'Australia'),
            ('Austria',	'Austria'),
            ('Azerbaijan',	'Azerbaijan'),
            ('Burundi',	'Burundi'),
            ('Belgium',	'Belgium'),
            ('Benin',	'Benin'),
            ('Burkina Faso',	'Burkina Faso'),
            ('Bangladesh',	'Bangladesh'),
            ('Bulgaria',	'Bulgaria'),
            ('Bahrain',	'Bahrain'),
            ('Bahamas, The',	'Bahamas The'),
            ('Bosnia and Herzegovina',	'Bosnia and Herzegovina'),
            ('Belarus',	'Belarus'),
            ('Belize',	'Belize'),
            ('Bermuda',	'Bermuda'),
            ('Bolivia',	'Bolivia'),
            ('Brazil',	'Brazil'),
            ('Barbados',	'Barbados'),
            ('Brunei Darussalam',	'Brunei Darussalam'),
            ('Bhutan',	'Bhutan'),
            ('Botswana',	'Botswana'),
            ('Central African Republic',	'Central African Republic'),
            ('Canada',	'Canada'),
            ('Switzerland',	'Switzerland'),
            ('Chile',	'Chile'),
            ('China',	'China'),
            ('Cote d Ivoire',	'Cote d Ivoire'),
            ('Cameroon',	'Cameroon'),
            ('Congo, Dem. Rep.',	'Congo Dem. Rep.'),
            ('Congo, Rep.',	'Congo Rep.'),
            ('Colombia',	'Colombia'),
            ('Comoros',	'Comoros'),
            ('Cabo Verde',	'Cabo Verde'),
            ('Costa Rica',	'Costa Rica'),
            ('Curacao',	'Curacao'),
            ('Cayman Islands',	'Cayman Islands'),
            ('Cyprus',	'Cyprus'),
            ('Czech Republic',	'Czech Republic'),
            ('Germany',	'Germany'),
            ('Djibouti',	'Djibouti'),
            ('Dominica',	'Dominica'),
            ('Denmark',	'Denmark'),
            ('Dominican Republic',	'Dominican Republic'),
            ('Algeria',	'Algeria'),
            ('Ecuador',	'Ecuador'),
            ('Egypt, Arab Rep.',	'Egypt Arab Rep.'),
            ('Eritrea',	'Eritrea'),
            ('Spain',	'Spain'),
            ('Estonia',	'Estonia'),
            ('Ethiopia',	'Ethiopia'),
            ('Finland',	'Finland'),
            ('Fiji',	'Fiji'),
            ('France',	'France'),
            ('Micronesia, Fed. Sts.',	'Micronesia Fed. Sts.'),
            ('Gabon',	'Gabon'),
            ('United Kingdom',	'United Kingdom'),
            ('Georgia',	'Georgia'),
            ('Ghana',	'Ghana'),
            ('Guinea',	'Guinea'),
            ('Gambia, The',	'Gambia The'),
            ('Guinea-Bissau',	'Guinea-Bissau'),
            ('Equatorial Guinea',	'Equatorial Guinea'),
            ('Greece',	'Greece'),
            ('Grenada',	'Grenada'),
            ('Guatemala',	'Guatemala'),
            ('Guyana',	'Guyana'),
            ('Hong Kong SAR, China',	'Hong Kong SAR China'),
            ('Honduras',	'Honduras'),
            ('Croatia',	'Croatia'),
            ('Haiti',	'Haiti'),
            ('Hungary',	'Hungary'),
            ('Indonesia',	'Indonesia'),
            ('India',	'India'),
            ('Ireland',	'Ireland'),
            ('Iran, Islamic Rep.',	'Iran Islamic Rep.'),
            ('Iraq',	'Iraq'),
            ('Iceland',	'Iceland'),
            ('Israel',	'Israel'),
            ('Italy',	'Italy'),
            ('Jamaica',	'Jamaica'),
            ('Jordan',	'Jordan'),
            ('Japan',	'Japan'),
            ('Kazakhstan',	'Kazakhstan'),
            ('Kenya',	'Kenya'),
            ('Kyrgyz Republic',	'Kyrgyz Republic'),
            ('Cambodia',	'Cambodia'),
            ('Kiribati',	'Kiribati'),
            ('St. Kitts and Nevis',	'St. Kitts and Nevis'),
            ('Korea, Rep.',	'Korea Rep.'),
            ('Kuwait',	'Kuwait'),
            ('Lao PDR',	'Lao PDR'),
            ('Lebanon',	'Lebanon'),
            ('Liberia',	'Liberia'),
            ('Libya',	'Libya'),
            ('St. Lucia',	'St. Lucia'),
            ('Sri Lanka',	'Sri Lanka'),
            ('Lesotho',	'Lesotho'),
            ('Lithuania',	'Lithuania'),
            ('Luxembourg',	'Luxembourg'),
            ('Latvia',	'Latvia'),
            ('Macao SAR, China',	'Macao SAR China'),
            ('Morocco',	'Morocco'),
            ('Moldova',	'Moldova'),
            ('Madagascar',	'Madagascar'),
            ('Maldives',	'Maldives'),
            ('Mexico',	'Mexico'),
            ('Marshall Islands',	'Marshall Islands'),
            ('North Macedonia',	'North Macedonia'),
            ('Mali',	'Mali'),
            ('Malta',	'Malta'),
            ('Myanmar',	'Myanmar'),
            ('Montenegro',	'Montenegro'),
            ('Mongolia',	'Mongolia'),
            ('Mozambique',	'Mozambique'),
            ('Mauritania',	'Mauritania'),
            ('Mauritius',	'Mauritius'),
            ('Malawi',	'Malawi'),
            ('Malaysia',	'Malaysia'),
            ('Namibia',	'Namibia'),
            ('Niger',	'Niger'),
            ('Nigeria',	'Nigeria'),
            ('Nicaragua',	'Nicaragua'),
            ('Netherlands',	'Netherlands'),
            ('Norway',	'Norway'),
            ('Nepal',	'Nepal'),
            ('Nauru',	'Nauru'),
            ('New Zealand',	'New Zealand'),
            ('Oman',	'Oman'),
            ('Pakistan',	'Pakistan'),
            ('Panama',	'Panama'),
            ('Peru',	'Peru'),
            ('Philippines',	'Philippines'),
            ('Palau',	'Palau'),
            ('Papua New Guinea',	'Papua New Guinea'),
            ('Poland',	'Poland'),
            ('Puerto Rico',	'Puerto Rico'),
            ('Portugal',	'Portugal'),
            ('Paraguay',	'Paraguay'),
            ('West Bank and Gaza',	'West Bank and Gaza'),
            ('Qatar',	'Qatar'),
            ('Romania',	'Romania'),
            ('Russian Federation',	'Russian Federation'),
            ('Rwanda',	'Rwanda'),
            ('Saudi Arabia',	'Saudi Arabia'),
            ('Sudan',	'Sudan'),
            ('Senegal',	'Senegal'),
            ('Singapore',	'Singapore'),
            ('Solomon Islands',	'Solomon Islands'),
            ('Sierra Leone',	'Sierra Leone'),
            ('El Salvador',	'El Salvador'),
            ('San Marino',	'San Marino'),
            ('Somalia',	'Somalia'),
            ('Serbia',	'Serbia'),
            ('Sao Tome and Principe',	'Sao Tome and Principe'),
            ('Suriname',	'Suriname'),
            ('Slovak Republic',	'Slovak Republic'),
            ('Slovenia',	'Slovenia'),
            ('Sweden',	'Sweden'),
            ('Eswatini',	'Eswatini'),
            ('Sint Maarten (Dutch part)',	'Sint Maarten (Dutch part)'),
            ('Seychelles',	'Seychelles'),
            ('Turks and Caicos Islands',	'Turks and Caicos Islands'),
            ('Chad',	'Chad'),
            ('Togo',	'Togo'),
            ('Thailand',	'Thailand'),
            ('Tajikistan',	'Tajikistan'),
            ('Turkmenistan',	'Turkmenistan'),
            ('Timor-Leste',	'Timor-Leste'),
            ('Tonga',	'Tonga'),
            ('Trinidad and Tobago',	'Trinidad and Tobago'),
            ('Tunisia',	'Tunisia'),
            ('Turkey',	'Turkey'),
            ('Tuvalu',	'Tuvalu'),
            ('Tanzania',	'Tanzania'),
            ('Uganda',	'Uganda'),
            ('Ukraine',	'Ukraine'),
            ('Uruguay',	'Uruguay'),
            ('United States',	'United States'),
            ('Uzbekistan',	'Uzbekistan'),
            ('St. Vincent and the Grenadines',	'St. Vincent and the Grenadines'),
            ('British Virgin Islands',	'British Virgin Islands'),
            ('Vietnam',	'Vietnam'),
            ('Vanuatu',	'Vanuatu'),
            ('Samoa',	'Samoa'),
            ('Kosovo',	'Kosovo'),
            ('South Africa',	'South Africa'),
            ('Zambia',	'Zambia'),
            ('Zimbabwe',	'Zimbabwe')

        ]
    )
    salary = DecimalField("Salary in source country's local currency", validators=[DataRequired("Please enter the salary")])